### PR TITLE
Add support for SNMP community string as a parameter

### PR DESCRIPTION
**Pull request by visago**
The whole idea is to allow configurations of target/community/module from prometheus instead of snmp_exporter's snmp.yml. Currently you can only specify target/module in snmp_exporter. This adds the community string (So its only for v1/v2) 

I've updated the README.md with an example of having a list of targets via a JSON file.

### CODE REVIEW

**Comment by brian-brazil** [comment]
URL parameters are not considered secure in Prometheus, and in addition you can already do this via multiple modules.

**Comment by visago** [comment]
> URL parameters are not considered secure in Prometheus, and in addition you can already do this via multiple modules.

That explains why this feature wasn't around there !  How about if used with HTTPS terminated exporters ?

Agreed that this is doable via multiple modules, but it means we have to do service discovery on the exporters too.

**Comment by brian-brazil** [comment]
> That explains why this feature wasn't around there ! How about if used with HTTPS terminated exporters ?

It'd still be exposed on the Prometheus UI.

> Agreed that this is doable via multiple modules, but it means we have to do service discovery on the exporters too.

That's a configuration management issue. I'd suggest having fewer passwords.

**Comment by CRCinAU** [comment]
I just stumbled across this because we use an SNMP community other than 'public' - so nothing seems to work.

Is the only way to get this working by creating a new snmp.yml file? There seems to be no way to set the community to anything other than public :\

**Comment by visago** [comment]
> I just stumbled across this because we use an SNMP community other than 'public' - so nothing seems to work.
> 
> Is the only way to get this working by creating a new snmp.yml file? There seems to be no way documented to set the community to anything other than public :\
> 
> Considering the snmp community to be 'secure' is probably a mistake - as its transmitted plain over the network, and also available multiple other places.

Yes, the only 'secure' way is to have it hidden in the snmp.yml file. This way each object you don't see the community string in the URL or prometheus target list (as a label)

My PR adds in community as a parameter (i.e. http://localhost:9116/snmp?target=1.2.3.4&community=superpublic) but is considered insecure (Esp if its a non-https end point) The good thing is you can then add your targets on the prometheus side instead of snmp.yml.

**Comment by CRCinAU** [comment]
SNMP communities aren't secure at all - its transmitted in plain text over the network, and is in no way, shape or form considered a secret - lets not confuse where its stored in a config file or parameter as a security feature.

I totally agree that the community should be able to be set from prometheus via the parameters. It's a good functional improvement that shouldn't be handwaved over for some misguided attempt at security.

**Comment by brian-brazil** [comment]
Secrets are secrets, no matter how they're transmitted. This is the stance in terms of general configuration management anyway, it'd be the same response for any other setting.

**Comment by CRCinAU** [comment]
For clarity, a snmp community is not a secret.

It seems to be a different stance than every other NMS in existence which has a standard config set of IP, Port, Version, community.

**Comment by cleonello** [comment]
This would be useful for real world management of SNMP devices.  

@CRCinAU is 100% correct.  the SNMP community is a name grouping agents and applications together, it is not a "secret".  It does, as a side effect of being a user defined string, provide the most trivial form of authentication.  However, devices are free to treat all SNMP messages as authentic messages and almost always do. 

This feature would make it easier for us to use Prometheus and do our jobs without impacting the complete absence of security in SNMP.  Please consider implementing.

**Comment by xaque208** [comment]
I think you can get around this by just creating a new group in the generator config with the community string you want for the given group.  Name it something useful, and then include it with the module on the Prometheus side configuration.

**Comment by brian-brazil** [comment]
> I think you can get around this by just creating a new group in the generator config with the community string you want for the given group. Name it something useful, and then include it with the module on the Prometheus side configuration.

That's the expected way to handle devices with different configurations.

**Comment by CRCinAU** [comment]
Its not a convenient way to do things though... Changing the community via prometheus.yml is a much better way to do things rather than probably duplicating mass parts of SNMP.yml just to change a community.

**Comment by xaque208** [comment]
If you authenticate to devices using separate credentials, then perhaps their differences warrant separate modules.  Also the config modules in generator.yaml still allow you to expand the portions of the OID tree to walk with the `walk` field, which at least helps reduce the duplication of the config.

**Comment by cleonello** [comment]
> 
> 
> > I think you can get around this by just creating a new group in the generator config with the community string you want for the given group. Name it something useful, and then include it with the module on the Prometheus side configuration.
> 
> That's the expected way to handle devices with different configurations.

Yes, and this hi how I do things currently but it isn't the most appropriate way in my opinion.


> 
> 
> If you authenticate to devices using separate credentials, then perhaps their differences warrant separate modules. Also the config modules in generator.yaml still allow you to expand the portions of the OID tree to walk with the `walk` field, which at least helps reduce the duplication of the config.

The reason this is not desirable is that the community string is an attribute of the target device, not an attribute of the metric (oid).  It does not belong in the generator.yml/snmp.yml describing the oids, it belongs in the json file describing the target devices.  It is valid to have different community strings for each and every device.  It is also valid that these strings may change periodically based on some outside business practice.  These changes can be easily picked up in the json file through the file_sd_config.

**Comment by cleonello** [comment]
> > > I think you can get around this by just creating a new group in the generator config with the community string you want for the given group. Name it something useful, and then include it with the module on the Prometheus side configuration.
> > 
> > 
> > That's the expected way to handle devices with different configurations.
> 
> Yes, and this hi how I do things currently but it isn't the most appropriate way in my opinion.

Not to walk back my comment but to clarify, the existing configuration method works fine for many use cases.  For those not wanting to expose the community string through http it is beneficial.  However, the feature being proposed by @visago provides flexibility which, in my opinion, is needed for the reasons stated in my previous comment.

**Comment by visago** [comment]
Thank you all for the comments. Apologies for the slow update on this. Its good to see that others have the same need as me (ability to handle discovery and management via prometheus.yml) 

I've added AES-GCM encryption for the community string. There's a folder with a simple cryptotool to encrypt (or decrypt to verify) your community string with a passphrase. The passphrase should be passed to the snmp_exporter via commandline (Either direct or preferably via a file containing the passphrase)

I hope this satisfy the security requirements.

**Comment by brian-brazil** [comment]
> I've added AES-GCM encryption for the community string. 

We don't invent security stuff, any secrets should be in plain text for us. It's the user's responsibility to decode it from whatever they're using.

> This is the stance in terms of general configuration management anyway, it'd be the same response for any other setting.

This still applies.

**Comment by cameronkerrnz** [comment]
With all this mention of community-strings, please remember that method used needs to be generalisable to SNMPv3 as well, which _does_ have a notion of secret credentials.

**Comment by brian-brazil** [comment]
As indicated above, this change will not be accepted as it is not in line with either our configuration approach or security policies.

**Pull request closed without merging**
