### PR TITLE
eaton-fix

### LINKED ISSUE #836: EATON mib location is no longer valid
In `generator.yml` it references the EATON MIB as: https://powerquality.eaton.com/Support/Software-Drivers/Downloads/ePDU/EATON-EPDU-MIB.zip

But that now returns a 404 page.

### PR DESCRIPTION
**Pull request by h-leth**
This is my fix for the Eaton issues

Fixes #836 and #829
And are the code that is posted in PR #837

### CODE REVIEW

**Comment by h-leth** [comment]
Solves  #831

Let me know if anything need to be changed

**Comment by scottlaird** [comment]
I added the original Eaton support; this change looks good to me.  I was about to do something similar to fix the build problem.

**Comment by scottlaird** [comment]
As mentioned in #837, Eaton (really Akamai) seems to block Curl's User-Agent.  Also, it looks like Eaton's upstream source for this moved to https://www.eaton.com/content/dam/eaton/products/backup-power-ups-surge-it-power-distribution/Firmware/eaton-pdu-g3-firmware-mib.zip, which would need an intermediate unzip step to get EATON-EPDU-MIB.zip.  It's almost certainly easier to just fetch this from a different source, which is what this PR already does.

**Comment by SuperQ** [comment]
Since Eaton can't make their MIBs accessible, I think it's more appropriate that we simply remove them from the examples.

**Comment by h-leth** [comment]
>Since Eaton can't make their MIBs accessible, I think it's more appropriate that we simply remove them from the examples.

Sure I can remove them.

But what to do about issue #831, want to fix it in this PR or should I open a new one?
Or should that one be removed too? It's something with the new version of [AIRESPACE-WIRELESS-MIB.my](https://github.com/cisco/cisco-mibs/blob/main/v2/AIRESPACE-WIRELESS-MIB.my) on https://github.com/cisco/cisco-mibs

**Comment by SuperQ** [comment]
Fixed with https://github.com/prometheus/snmp_exporter/pull/843

**Pull request closed without merging**
