### PR TITLE
added SIGQUIT, SIGTERM handling

### PR DESCRIPTION
**Pull request by iglov**
SIG made me SICK ^_^
killall snmp_exporter ->

```⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣠⣤⢤⣤⠤⠤⢤⣄⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣴⣖⣛⣋⡉⠁⠀⠀⢀⣿⠀⢀⣴⣿⠿⢯⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡶⠟⠋⠉⠉⠉⠉⠉⠉⠉⠛⠓⠛⣿⢿⣷⣿⠿⠥⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡾⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣾⣷⣾⡏⠀⠀⠀⠀⠀⠀⠀⠈⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣼⢯⣿⠀⠀⠀⠀⠀⡀⠀⠀⠀⠈⢻⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣀⣀⣠⣤⣶⣟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⡟⠀⠀⢰⣿⠿⠛⠛⢶⣄⠀⠀⢿⣿⣆⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠈⠉⠉⣹⡿⠛⠛⠻⢷⣶⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⠟⠀⢀⡴⠛⠁⠀⠀⣀⠀⠹⣦⡀⠘⣮⠻⣆⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡄⢀⣾⠟⠁⠀⠀⠀⠀⠈⠻⣿⡟⠛⠀⠀⠀⠀⠀⠀⣿⡟⣿⠏⠀⣰⠏⠀⠀⠀⠀⠀⣿⠀⠀⠈⣻⣆⠘⢷⣿⠀⠀⠀⠀⠀⠀
⠀⠀⢸⣧⡟⠁⠀⠀⠀⠀⠀⢀⣀⣀⣈⣻⣦⡀⠀⠀⠀⠀⠀⠘⣷⣿⠀⢰⠏⠀⠀⠀⠀⠀⠀⠛⠓⠲⠶⠃⠙⣦⠀⢻⣇⠀⠀⠀⠀⠀
⠀⠀⣼⡏⠀⠀⠀⠀⢀⣴⠟⠋⠁⠀⠀⠉⠛⢷⣄⡀⠀⠀⠀⠘⠛⠋⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣆⠀⢻⣦⠀⠀⠀⠀
⠀⢰⣿⡇⠀⠀⠀⣴⡏⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣛⣿⠀⠀⠀⠀⠀⠀⠘⢷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡆⠈⣿⣧⡀⠀⠀
⡇⠈⣿⠁⠀⠀⢠⡟⠉⠙⢿⡄⠀⠀⠀⠀⠀⠀⠈⠉⣿⠀⠀⠀⠀⠀⠀⠀⠈⢷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠃⠀⢸⡿⣧⠀⠀
⡇⢰⠇⠀⠀⠀⠸⣧⡤⠶⠛⠀⠀⠀⠀⠀⠀⠀⠀⣼⠃⠀⠀⣀⣠⣤⣤⣤⣤⣄⣉⡳⢦⣤⣀⡀⠀⠀⠀⢀⣠⠾⠃⠀⠀⠀⢷⡘⣧⠀
⣿⣿⠀⠀⠀⠀⠀⢹⡀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡼⠋⠀⣠⠾⣯⠀⠀⠀⢻⣄⠀⢉⠙⠷⣤⣉⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠘⣧⢽⠀
⣿⡇⠀⠀⠀⠀⠀⠸⣇⠀⠀⠀⠀⠀⠀⠀⣰⠟⠀⢀⣾⠁⠀⠘⢷⣄⡀⢸⠉⠛⠛⠁⠀⠀⠙⠛⠶⣶⣒⠲⣦⡀⠀⠀⠀⠀⠀⢹⣼⠀
⣿⡇⠀⠀⠀⠀⠀⠀⠙⢶⣄⣀⣀⣀⣠⡾⠃⠀⢠⡏⢻⣆⠀⠀⢸⡏⠉⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠈⢻⡄⠀⠀⠀⠀⠈⣿⠀
⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠙⣿⠷⠦⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡄⠀⠀⠀⠀⢹⡇
⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⠶⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣄⡀⠀⠀⠀⠀⠀⠀⠀⠻⡆⠀⠀⠀⢸⡇
⣿⢷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⠉⠈⠻⣦⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⢸⡇
⢿⠸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠇⠀⠀⠀⠀⠀⠀⠀⣴⠟⠙⠛⠚⠁⠀⠀⠀⢀⣸⣷⣄⡟⠉⠛⢶⡀⣿⠀⠀⠀⢸⡇
⠸⡆⢿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⠀⠀⠀⠀⠀⠀⠀⣼⠁⠀⠀⠀⠀⢀⣀⡀⠀⡾⠁⠀⢹⡇⠀⠀⠀⢁⡏⠀⠀⠀⢸⡇
⠀⣷⠘⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡏⠀⠀⠀⠀⠀⠀⠸⠃⠀⠀⠀⠀⣾⠋⠉⠹⡾⠃⣀⣤⠼⠧⠤⠴⠖⠛⠁⠀⠀⠀⠈⣿
⠀⠸⣆⣹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠁⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⡀⢸⡇⠀⠀⢀⣴⠞⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠘⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⠃⠀⠀⠀⠀⠀⠀⣰⠟⠁⠀⠈⠷⣾⢀⣠⠾⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⡏
⠀⠀⠀⠘⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⣴⠏⠀⣠⡶⠛⢷⣄⣰⠇⠀⠀⠀⢀⣠⠿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡟⠀
⠀⠀⠀⠀⣿⠘⣧⡀⠀⠀⠀⠀⠀⠀⠿⢶⣾⣉⣀⠀⠀⠈⠛⢀⣤⠴⠞⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡟⠀⠀
⠀⠀⠀⠀⢸⡆⠈⠻⢦⣄⡀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠛⠛⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡿⠁⠀⠀
⠀⠀⠀⠀⠀⢿⡄⠀⠀⠈⠛⠶⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⠃⠀⠀⠀
⠀⠀⠀⠀⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠀⠀⠀⠀
```

### CODE REVIEW

**Comment by dswarbrick** [comment]
What is the main motivation of this, other than emitting a log entry before acting on the signal? SIGKILL / SIGTERM will terminate the exporter, and SIGQUIT will dump core (and then terminate) - all as per described behavior of `signal(7)`.

**Comment by iglov** [comment]
@dswarbrick hmm, well, maybe just use `kill` for killing the process cuz now it doesn't work?

**Comment by dswarbrick** [comment]
Works for me.
```
$ pgrep snmp_exporter
4421
$ kill 4421
```
```
ts=2023-05-29T12:45:04.132Z caller=main.go:148 level=info msg="Starting snmp_exporter" version="(version=, branch=, revision=)"
ts=2023-05-29T12:45:04.132Z caller=main.go:149 level=info build_context="(go=go1.20.3, user=, date=)"
ts=2023-05-29T12:45:04.231Z caller=tls_config.go:232 level=info msg="Listening on" address=[::]:9116
ts=2023-05-29T12:45:04.231Z caller=tls_config.go:235 level=info msg="TLS is disabled." http2=false address=[::]:9116
Terminated
```

**Comment by SuperQ** [comment]
@dswarbrick I think the issue is that SIGTERM causes the exporter to exit with a non-zero status code, which makes supervisors consider it failed.

I think we should add proper signal handling to the exporter-toolkit.

**Comment by iglov** [comment]
@SuperQ yep-yep-yep, that's exactly what i mean, thanks Ben ^_^

**Comment by dswarbrick** [comment]
I wonder why you would manually kill an exporter if it has been launched by a supervisor. Wouldn't it be more logical to use the supervisor's recommended method of stopping the service? ... i.e., it's probably legitimate for the supervisor to be concerned when the service "spontaneously" terminates with a non-zero status.

**Comment by iglov** [comment]
```
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡠⠴⠒⠒⠲⠤⠤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡴⠋⠀⠀⠀⠀⠠⢚⣂⡀⠈⠲⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⡀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡎⡴⠆⠀⠀⠀⠀⠀⢎⠐⢟⡇⠀⠈⢣⣠⠞⠉⠉⠑⢄⠀⠀⣰⠋⡯⠗⣚⣉⣓⡄
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⢠⢞⠉⡆⠀⠀⠀⠀⠀⠓⠋⠀⠀⠀⠀⢿⠀⠀⠀⠀⠈⢧⠀⢹⣠⠕⠘⢧⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠘⠮⠔⠁⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠸⡀⠀⠀⠀⠀⠈⣇⠀⢳⠀⠀⠘⡆⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡴⠋⠉⠓⠦⣧⠀⠀⠀⠀⢦⠤⠤⠖⠋⠇⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠸⡄⠈⡇⠀⠀⢹⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠁⠀⠀⠀⠀⠙⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠈⣆⠀⠀⠀⢱⠀⡇⠀⠀⠀⡇⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠀⠀⠀⠀⠀⠀⠘⢆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠁⠀⠀⠸⡄⠀⠀⠀⠳⠃⠀⠀⠀⡇⠀
⠀⠀⠀⠀⠀⢠⢏⠉⢳⡀⠀⠀⢹⠀⠀⠀⠀⢠⠀⠀⠀⠑⠤⣄⣀⡀⠀⠀⠀⠀⠀⣀⡤⠚⠀⠀⠀⠀⠀⢸⢢⡀⠀⠀⠀⠀⠀⢰⠁⠀
⠀⠀⣀⣤⡞⠓⠉⠁⠀⢳⠀⠀⢸⠀⠀⠀⠀⢸⡆⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⢸⠀⠙⠦⣤⣀⣀⡤⠃⠀⠀
⠀⣰⠗⠒⣚⠀⢀⡤⠚⠉⢳⠀⠈⡇⠀⠀⠀⢸⡧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠸⠵⡾⠋⠉⠉⡏⠀⠀⠀⠈⠣⣀⣳⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⡼⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠳⡄⠀⠀⠀⠀⠀⠀⠀⡰⠁⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠈⠓⠲⠤⠤⠤⠴⠚⠁⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
```
Actually, i dunno. I just have several cases where it should be useful. Anyway if you don't see any good points in this PR, you can just close it, it's ok, nvm ^_^

**Comment by SuperQ** [comment]
Yes, I would like to implement this in the exporter-toolkit. Will close this here.

**Pull request closed without merging**
