### PR TITLE
add support for module include of configuration file

### PR DESCRIPTION
**Pull request by 0086**
Only "walk" and "metrics" will be included, SNMP parameters will not be included.

### CODE REVIEW

**Comment by brian-brazil** [comment]
What are you trying to do?

**Comment by 0086** [comment]
I don't want to waste time copying oid between different modules.

**Comment by 0086** [comment]
sample configuration file:
```
default:
  walk:
  - 1.3.6.1.2.1.1.3
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: The time since the system was last re-initialized.

10.10.10.1:
  include:
  - default

  walk:
  - 1.3.6.1.2.1.1.5
  metrics:
  - name: sysName
    oid: 1.3.6.1.2.1.1.5
    type: DisplayString
    help: The name of system

```

**Comment by brian-brazil** [comment]
You should be using the generator to create your snmp.yml. There's no plans to offer such a feature, as either your generator config is simple enough that it doesn't matter or it's sufficiently complex that you need configuration management anyway.

**Comment by 0086** [comment]
We have a large number of machines that need to be monitored and the machines are dynamically added and deleted. 
Some OIDs are common to all machines. Some OIDs are common to a group of machines. Each machine may also have some unique OIDs.

**Comment by SuperQ** [comment]
This can already be done with YAML merge syntax.  There's no need for a code change.

```
sysuptime: &sysuptime
  walk:
  - 1.3.6.1.2.1.1.3
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: The time (in hundredths of a second) since the network management portion
      of the system was last re-initialized. - 1.3.6.1.2.1.1.3

some_other_module:
  <<: *sysuptime
  walk:
  - 1.3.6.1.2.1.2
  metrics:
    ...
```

**Comment by 0086** [comment]
@SuperQ Thanks a lot, I will try it later.

**Pull request closed without merging**
