### PR TITLE
Update servertech-sentry3-mib location - fixes #434

### LINKED ISSUE #434: servertech-sentry3-mib location update
`servertech-sentry3-mib` is not available via FTP any more. Regarding https://www.servertech.com/support/sentry-mib-oid-tree-downloads/ the right link is now https://cdn10.servertech.com/assets/documents/documents/817/original/Sentry3.mib

### PR DESCRIPTION
**Pull request by Cougar**
Update for MIB URL. Old FTP is password protected and not accessible any more. `make mibs` fails because of that.

### CODE REVIEW

**Comment by SuperQ** [comment]
Looks like the keepalived MIB updated with new metrics.

**Comment by Cougar** [comment]
This PR has now two commits: one to update URL and another to update `snmp.yml` for newer keepalived MIB. Or should we separate these commits to two PRs?

**Comment by SuperQ** [comment]
One PR is fine, thanks!

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
