### PR TITLE
Added vyatta snmp configuration

### PR DESCRIPTION
**Pull request by cagiti**

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is basically the same as the default module. I don't see anything vyatta specific here.

**Comment by cagiti** [comment]
I agree, nothing specific but the `indexes: labelname` and `lookups: labels` configuration items needed to be changed due to `ifDescr `clashes (`* collected metric ifSpeed label:<name:"ifDescr" value:"Intel Corporation Ethernet Controller 10 Gigabit X540-AT2" > untyped:<value:0 >  was collected before with the same name and label values`) for the vyatta devices. Are you aware of any other way to resolve these kind of issues.

**Comment by brian-brazil** [comment]
Remove the lookup. This is only the only device affected by this.

**Comment by cagiti** [comment]
I've removed the lookup, but it doesn't provide the interface name detail.

**Comment by brian-brazil** [comment]
Yes, that's expected. We can only use it as the label if they're unique.

**Comment by cagiti** [comment]
True, however the configuration I've pushed up you get the interface detail...something which I think is important.

**Comment by brian-brazil** [comment]
This has been discussed in depth before. Basically you either the number or you get the unique names.

**Comment by cagiti** [comment]
Ok, I think the unique names should be the only way forward...the metrics aren't very useful if the numbers represent the metrics. Are you likely yo merge this?

**Comment by brian-brazil** [comment]
This won't be merged, it's not adding anything new.

**Comment by cagiti** [comment]
How would you expect people to be able to scrape snmp data from a vyatta device?

**Comment by brian-brazil** [comment]
If the default doesn't work, they can remove the lookups.

**Comment by cagiti** [comment]
How will they know that they have to remove the lookups?

**Comment by brian-brazil** [comment]
So far we've only had it hit 2-3 people.

**Comment by cagiti** [comment]
Still, this change provides a mechanism to mitigate against it. Shouldn't you be looking to make it easier for people to use this tool...as once I'd figured out how to reconfigure the snmp configuration it was great.

**Comment by brian-brazil** [comment]
This change doesn't help, as it produces spurious labels. See #37

**Comment by mohanprasaths** [comment]
Having the same issue with vyatta router . 
Can't we have multiple lookups to solve the problem ? or Is there any other way?
Thanks in advance.

**Comment by brian-brazil** [comment]
You need to remove the lookups.

**Comment by mohanprasaths** [comment]
@brian-brazil  but also I need "ifDescr" instead of "ifIndex" in my response .

**Comment by brian-brazil** [comment]
If only ifIndex is unique then the only option is ifIndex as a label.

**Comment by mohanprasaths** [comment]
@brian-brazil Thank you

**Comment by SuperQ** [comment]
Like @brian-brazil said, this is the same as the default module and won't be included in the official exporter.

You may be interested in this non-official [default.yml](https://github.com/SuperQ/tools/blob/master/snmp_exporter/default.yml) config.

**Comment by mohanprasaths** [comment]
@SuperQ  Thanks it worked .

**Comment by audynespinoza** [comment]
i have a similar issue where i'm trying to lookup ifAlias (which is the description of the interface).  the idea is to use the description in grafana to identify each time series.  my problem is that it's also complaining because more than two interfaces have the same value (empty value).  it's because internface null0 and vo0 don't have a description.  what's worst is i can't seem to add a description to these interfaces.  I really wish the code was smart enough to generate a unique value instead of stopping everything from working.
when i do a snmpwalk -v 2c -c (community) 10.10.10.10 1.3.6.1.2.1.31.1.1.1.18
the two interfaces returning an empty value are a show stopper. what a shame =(
IF-MIB::ifAlias.8 = STRING: 
IF-MIB::ifAlias.9 = STRING:

**Comment by brian-brazil** [comment]
In that case you must use default_ifindex, as ifAlias isn't unique. 

> I really wish the code was smart enough to generate a unique value instead of stopping everything from working.

How would that work?

**Comment by RichiH** [comment]
We talked about this quite a bit during FOSDEM and the consensus seems to be shifting towards including a minimal set of labels to ensure long-term uniqueness and the ability to reference properly. This should solve all those cases.

**Comment by audynespinoza** [comment]
yeah if i change to index, it doesn't crash the snmp walk but it's kinda useless for me.  it gives me this:
ifOutOctets{ifIndex="1"} 1.754850893e+09
ifOutOctets{ifIndex="10"} 0
ifOutOctets{ifIndex="11"} 3.143972043e+09
ifOutOctets{ifIndex="12"} 3.143952115e+09
ifOutOctets{ifIndex="13"} 0
ifOutOctets{ifIndex="2"} 0
ifOutOctets{ifIndex="23"} 7.84900675e+08
ifOutOctets{ifIndex="24"} 2.25993235e+09
ifOutOctets{ifIndex="25"} 2.370782458e+09
ifOutOctets{ifIndex="26"} 3.136622812e+09
ifOutOctets{ifIndex="27"} 3.115190623e+09
ifOutOctets{ifIndex="28"} 1.013687238e+09
ifOutOctets{ifIndex="29"} 8.8545769e+07
ifOutOctets{ifIndex="3"} 4.059262888e+09
ifOutOctets{ifIndex="30"} 3.175370623e+09
ifOutOctets{ifIndex="31"} 3.91069402e+08
ifOutOctets{ifIndex="32"} 1.855465651e+09
ifOutOctets{ifIndex="33"} 0
ifOutOctets{ifIndex="34"} 0
ifOutOctets{ifIndex="35"} 0
ifOutOctets{ifIndex="36"} 0
ifOutOctets{ifIndex="37"} 5.58911564e+08
ifOutOctets{ifIndex="38"} 0
ifOutOctets{ifIndex="39"} 0
ifOutOctets{ifIndex="4"} 3.899432177e+09
ifOutOctets{ifIndex="40"} 0
ifOutOctets{ifIndex="41"} 0
ifOutOctets{ifIndex="42"} 0
ifOutOctets{ifIndex="43"} 0
ifOutOctets{ifIndex="44"} 1.67761564e+08
ifOutOctets{ifIndex="45"} 1.31406127e+08
ifOutOctets{ifIndex="5"} 3.73991167e+09
ifOutOctets{ifIndex="6"} 1.18109663e+08
ifOutOctets{ifIndex="7"} 0
ifOutOctets{ifIndex="8"} 0
ifOutOctets{ifIndex="9"} 0

**Comment by audynespinoza** [comment]
also ifDesc gives me the interface name. 
ifOutOctets{ifIndex="1"} 1.754850893e+09
ifOutOctets{ifIndex="10"} 0
ifOutOctets{ifIndex="11"} 3.143972043e+09
ifOutOctets{ifIndex="12"} 3.143952115e+09
ifOutOctets{ifIndex="13"} 0
ifOutOctets{ifIndex="2"} 0
ifOutOctets{ifIndex="23"} 7.84900675e+08
ifOutOctets{ifIndex="24"} 2.25993235e+09
ifOutOctets{ifIndex="25"} 2.370782458e+09
ifOutOctets{ifIndex="26"} 3.136622812e+09
ifOutOctets{ifIndex="27"} 3.115190623e+09
ifOutOctets{ifIndex="28"} 1.013687238e+09
ifOutOctets{ifIndex="29"} 8.8545769e+07
ifOutOctets{ifIndex="3"} 4.059262888e+09
ifOutOctets{ifIndex="30"} 3.175370623e+09
ifOutOctets{ifIndex="31"} 3.91069402e+08
ifOutOctets{ifIndex="32"} 1.855465651e+09
ifOutOctets{ifIndex="33"} 0
ifOutOctets{ifIndex="34"} 0
ifOutOctets{ifIndex="35"} 0
ifOutOctets{ifIndex="36"} 0
ifOutOctets{ifIndex="37"} 5.58911564e+08
ifOutOctets{ifIndex="38"} 0
ifOutOctets{ifIndex="39"} 0
ifOutOctets{ifIndex="4"} 3.899432177e+09
ifOutOctets{ifIndex="40"} 0
ifOutOctets{ifIndex="41"} 0
ifOutOctets{ifIndex="42"} 0
ifOutOctets{ifIndex="43"} 0
ifOutOctets{ifIndex="44"} 1.67761564e+08
ifOutOctets{ifIndex="45"} 1.31406127e+08
ifOutOctets{ifIndex="5"} 3.73991167e+09
ifOutOctets{ifIndex="6"} 1.18109663e+08
ifOutOctets{ifIndex="7"} 0
ifOutOctets{ifIndex="8"} 0
ifOutOctets{ifIndex="9"} 0

I want to take it further and simply be able to output the interface description that i put into the router config.... but yeah.  Rich, were you saying this will be fixed soon?

**Comment by audynespinoza** [comment]
hey Rich to clarify when you mentioned, "including a minimal set of labels to ensure long-term uniqueness and the ability to reference properly", is that something that i can already do today, or is that in the works?

**Comment by SuperQ** [comment]
@audynespinoza Yes, check out the config file linked from my comment [above](https://github.com/prometheus/snmp_exporter/pull/72#issuecomment-273777798).

**Comment by audynespinoza** [comment]
@SuperQ YESSSS!! it worked.  thanks a bunch for this.

**Pull request closed without merging**
