### PR TITLE
Build and publish the generator Docker image

### PR DESCRIPTION
**Pull request by SuperQ**
* Add docker build to generator Makefile.
* Build and publish the generator with CircleCI.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
I've created `snmp-generator` on docker hub and quay.io.

**Comment by brian-brazil** [comment]
This ties the generator to releases, currently users always use head which I can see causing some confusion.

Is this our "standard" way of having multiple docker images? I don't think any other repo has one.

**Comment by SuperQ** [comment]
This creates an entirely separate docker image publishing, `docker pull prom/snmp-generator`. Users can choose to match the release tag, or they can use `docker pull prom/snmp-generator:master` to pull in the commit from head.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
