### PR TITLE
Adding installation of gopkg.in/yaml.v2 to Build Instructions

### PR DESCRIPTION
**Pull request by momorientes**
Might be obvious to someone used to go.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This should not be required, it should be picked up from the vendor directory.

**Comment by momorientes** [comment]
didn't work for me just now. Fairly new to golang tough, so not sure if I did something wrong.
All I did was: 
  - clone the repo
  - cd generator
  - apt-get install ...
  - go build

**Comment by brian-brazil** [comment]
Ah, so your GOPATH isn't setup. You should do that and make sure the repo is at the right path

**Comment by RichiH** [comment]
Arguably, this PR makes a good case to put a pre-built snmp_exporter on the Prometheus download page. Normal usage should not require a Go environment in the first place.

**Comment by brian-brazil** [comment]
We can't pre-build it, as it depends on the netsnmp you have installed on your machine.

**Comment by momorientes** [comment]
Maybe adding a section about correctly setting up a Go environment on the [getting started](https://prometheus.io/docs/introduction/getting_started/) page would prevent further issues as prometheus continues to grow.

**Pull request closed without merging**
