### PR TITLE
constant label parameter added

### PR DESCRIPTION
**Pull request by bkayranci**
@brian-brazil 

Here the use case is as follows;
* We have thousands of interfaces on the network elements that we need to monitor (say 10000)
* We're only interested in a subset of these interfaces (say 100)
* We know the "ifIndex" of these specific interfaces along with their descriptions etc. (we have network inventory)
* If snmp_exporter allows us to "specify" "constant labels" for the metrics, we're able to define "metrics" and assign "constant labels" to each metric.

Example config:

```yaml
10.0.0.2:
  get:
  - 1.3.6.1.2.1.31.1.1.1.6.1
  - 1.3.6.1.2.1.31.1.1.1.6.10
  metrics:
  - name: ifHCInOctets
    oid: 1.3.6.1.2.1.31.1.1.1.6.1
    type: counter
    const_labels:
      lag_name: LAG00
      port_name: Ge 1/1/0
      region_name: NY
      city_name: NYC
      ifIndex: 1 

  - name: ifHCInOctets
    oid: 1.3.6.1.2.1.31.1.1.1.6.10
    type: counter
    const_labels:
      lag_name: LAG01
      port_name: Ge 2/0
      region_name: NY
      city_name: NYC
      ifIndex: 10
```

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. Business logic like this is out of scope for the snmp exporter, it exposes SNMP data rather than trying to be a general network database.

You can specify the oids you want in the walk section already, and I'd suggest using ifDescr and friends for the rest.

**Comment by karanlik** [comment]
Hi @brian-brazil ,

We're working with @bkayranci on this issue and we believe this solution can help tickets like following;
https://github.com/prometheus/snmp_exporter/issues/432

Here the main idea is "allowing" snmp_exporter users to add "some constant label" to the metrics that they want to. This "const_labels" is optional. People like us (with network inventory in hand) can create their own "generator" projects, read information from their inventory DB, and create "snmp.yml" files accordingly. I see this is the only way to allow people not to walk all those thousands of interfaces and specify only a subset of these interfaces. 

Since Prometheus metrics are unique with name + labels, providing a "get" OID list won't help only. Here the alternatives would be;
1) define the metric names to bu unique as ifHCInOctets_if_123
2) definte the metric names to be the same as "ifHCInOctets" AND let the "const_labels" account for the "uniqueness".

Can you please share your comments in this respect ?

thanks,

**Comment by brian-brazil** [comment]
#432 is separate, and all the support needed within the snmp exporter to is already there for you to build on.

> Since Prometheus metrics are unique with name + labels, providing a "get" OID list won't help only.

I think you're getting confused. I'm talking about the walk config option of the generator config, which already handles this correctly.

**Comment by brian-brazil** [comment]
This is adding things which don't make sense in snmp-exporter terms, and I believe we already support what you need in the generator.

**Pull request closed without merging**
