### PR TITLE
Include the name of the index in the error message when the generator can't handle an index

### PR DESCRIPTION
**Pull request by thomaswhiteway**
I added this to help debug an error I was hitting, I can confirm that it helps.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO?

**Comment by thomaswhiteway** [comment]
Apparently to do this I need approval from someone who's now away until the new year, I'll come back to this in January.

**Comment by thomaswhiteway** [comment]
I now have approval for the DCO and have updated the commit.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
