### PR TITLE
Add type to parse date and time 

### LINKED ISSUE #1232: Parse date and time from DisplayString
### Host operating system: output of `uname -a`

Docker on Linux

### snmp_exporter version: output of `snmp_exporter -version`

```
snmp_exporter, version 0.26.0 (branch: HEAD, revision: 44f8732988e726bad3f13d5779f1da7705178642)
  build user:       root@90ba0aabb239
  build date:       20240511-11:16:35
  go version:       go1.22.3
  platform:         linux/amd64
  tags:             unknown
```

### What device/snmpwalk OID are you using?

```
sfosBaseFWLicExpiryDate OBJECT-TYPE
    SYNTAX		DisplayString
    MAX-ACCESS		read-only
    STATUS		current
    DESCRIPTION		"Base Firewall protection Lic expiry date"
    ::= { sfosDeviceBaseFWLic 2 }
```

### If this is a new device, please link to the MIB(s).

https://docs.sophos.com/nsg/sophos-firewall/MIB/SOPHOS-XG-MIB.zip

### What did you expect to see?

Parse the date and time and report the timestamp

### What did you see instead?

I'm currently working on including Sophos XG devices. But at the moment I haven't finished a PR because the snmp_exporter is unable to parse date and time from a DisplayString.

If a valid license has been provided the output looks like the example below.

```
# HELP sfosBaseFWLicExpiryDate Base Firewall protection Lic expiry date - 1.3.6.1.4.1.2604.5.1.5.1.2
# TYPE sfosBaseFWLicExpiryDate gauge
sfosBaseFWLicExpiryDate{sfosBaseFWLicExpiryDate="Dec 31 2999"} 1
```

If a license is not available the output will look like.

```
# HELP sfosCentralOrchestrationLicExpiryDate Central Orchestration Lic expiry date - 1.3.6.1.4.1.2604.5.1.5.9.2
# TYPE sfosCentralOrchestrationLicExpiryDate gauge
sfosCentralOrchestrationLicExpiryDate{sfosCentralOrchestrationLicExpiryDate="fail"} 1
```

Also there is a value for the current time.

```
# HELP sfosCurrentDate Current system date and time - 1.3.6.1.4.1.2604.5.1.2.1
# TYPE sfosCurrentDate gauge
sfosCurrentDate{sfosCurrentDate="Thu Aug  8 14:28:07 2024"} 1
```

### New feature

Would be great if the exporter can parse the date and time and report the timestamp similar to the ```DateAndTime``` type.

To solve the issue I would like to add a new type ```ParseDateAndTime``` and use the ```time.Parse()``` https://pkg.go.dev/time#Parse function to parse the value. If go is unable to parse the date I would skip the metric.

Example config:

```yaml
    overrides: # Allows for per-module overrides of bits of MIBs
      sfosBaseFWLicExpiryDate{sfosBaseFWLicExpiryDate:     
        type: ParseDateAndTime
        datetime_format: Jan 02 2006
      sfosCurrentDate{sfosCurrentDate:
        type: ParseDateAndTime
        datetime_format: Mon Jan 2 3:04:05 2006
```

What do you think about it? Is it worth to implement this feature and open a PR or is it out of scope for the snmp_exporter?

### PR DESCRIPTION
**Pull request by phibos**
I have added a new type ParseDateAndTime to parse timestamps from DisplayString and report it as unix timestamp.

Please have a look and report if something is missing.

This fixes #1232

For now it uses the go time.Parse() function. If we want to swap it out there are some packages.

* https://github.com/golang-module/carbon
* https://github.com/jinzhu/now

What do you think?

### CODE REVIEW

**Comment by SuperQ** [comment]
Nice, I like it so far. I haven't had a chance to evaluate the parser libraries.

**Comment by SuperQ** [comment]
I personally prefer strftime style parsing. I sent a couple of PRs to https://github.com/lestrrat-go/strftime to see if the maintainer is still active.

What do you think @bastischubert? Do you prefer Go or strftime style date parsing syntax?

**Comment by bastischubert** [comment]
I'm not in favor of any specific parsing syntax - whatever works and doesn't introduce unnecessary complexity if ok (-:

**Comment by phibos** [comment]
@SuperQ did you find the time to have a look at the time parser libraries? Do I have to change something or can this PR be merged?

**Comment by SuperQ** [comment]
I looked over https://github.com/lestrrat-go/strftime, it seems reasonable. I'm fine with either library, but I live a slight preference for strftime.

**Comment by phibos** [comment]
Thanks for you reply. I will update the PR and use the strftime functions to parse the date and time. But before I change the code. Do you see any reason why we should provide an config option to specify the format type?

Example:
```yaml
datetime_format_type: go | strftime
```

**Comment by SuperQ** [comment]
Adding multiple parser options is probably a bit more complexity than necessary. I'd like to start with one parser and see how things evolve.

**Comment by phibos** [comment]
Had to use https://github.com/itchyny/timefmt-go instead of https://github.com/lestrrat-go/strftime because it does not support parsing lestrrat-go/strftime#22

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
