### PR TITLE
Ensure example config is included, add systemd unit

### PR DESCRIPTION
**Pull request by jacekn**
MANIFEST.in specifies example_configs directory which does not exist. Create it, move snmp.yml there and also add basic systemd unit file

### CODE REVIEW

**Comment by brian-brazil** [comment]
A directory like that would be for SNMP exporter configs, not all types of configs.

This file is hardcoding paths, which I don't think we can presume.

**Comment by jacekn** [comment]
Where would you like to store the unit file?

There are hardcoded paths but I think it's OK for an _example_ unit file. Vendors can write their own and users can either modify it or put files where the unit file expects them.

**Comment by brian-brazil** [comment]
Chuck it in the root.

**Comment by jacekn** [comment]
Done

**Comment by RichiH** [comment]
This might be too late, but shouldn't it be `/etc/prometheus.d/`?

**Comment by jacekn** [comment]
Ubuntu 16.04 prometheus package uses /etc/prometheus/ for config, I think it makes sense to go with that but since it's an example I don't mind changing it if people have strong opinions.

**Comment by brian-brazil** [comment]
A .d would imply we're combining multiple files into one, which we aren't.

**Comment by brian-brazil** [comment]
Can you put the primary config back where it was, and squash your commits?

**Comment by RichiH** [comment]
@brian-brazil Just for completeness' sake, you were right about `.d`.

**Comment by jacekn** [comment]
Commit squashed

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
