### PR TITLE
Added basic support for Fortinet Fortigate devices

### PR DESCRIPTION
**Pull request by elisiano**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

**Comment by brian-brazil** [comment]
Can you tell me where we can download the MIBs for this device?

**Comment by SuperQ** [comment]
http://kb.fortinet.com/kb/documentLink.do?externalID=11607

**Comment by elisiano** [comment]
I could not find the proper file anywhere over the internet ( @SuperQ link requires to login ).
Usually you need to log into the administration interface and download the MIBs directly from the device.

I found a copy here though: http://www.oidview.com/mibs/12356/FORTINET-FORTIGATE-MIB.html but I'm not sure that's the latest version.

@brian-brazil: if you want I can email you the files or just put them on paste bin for a limited time.

**Pull request merged**
