### PR TITLE
Fix EATON download

### LINKED ISSUE #836: EATON mib location is no longer valid
In `generator.yml` it references the EATON MIB as: https://powerquality.eaton.com/Support/Software-Drivers/Downloads/ePDU/EATON-EPDU-MIB.zip

But that now returns a 404 page.

### PR DESCRIPTION
**Pull request by francois2metz**
fix #836 and #829

I had to use a custom user agent, as akamai seems to forbid curl.

### CODE REVIEW

**Comment by SuperQ** [comment]
Ugh, really? They're blocking curl UA?

**Comment by SuperQ** [comment]
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

**Comment by h-leth** [comment]
Any progress on this PR?

**Comment by francois2metz** [comment]
For some reasons the build fail on circleci. I tried to remove the manual user agent, but it fail later.

**Comment by h-leth** [comment]
Ok
I found the missing files in a Git repo and downloaded them from there. It works on my computer
If you want I can open a new PR or you can use my code and make a new commit

```
EATON_SENSOR_URL  := https://raw.githubusercontent.com/librenms/librenms/master/mibs/eaton/EATON-SENSOR-MIB
EATON_OIDS_URL    := https://raw.githubusercontent.com/librenms/librenms/master/mibs/eaton/EATON-OIDS

--snip--

$(MIBDIR)/EATON-SENSOR-MIB.txt:
         @echo ">> Downloading EATON-SENSOR-MIB.txt to $@"
         @curl $(CURL_OPTS) -o $@ $(EATON_SENSOR_URL)

 $(MIBDIR)/EATON-OIDS.txt:
         @echo ">> Downloading EATON-OIDS.txt to $@"
         @curl $(CURL_OPTS) -o $@ $(EATON_OIDS_URL)
```

**Comment by SuperQ** [comment]
Fixed with https://github.com/prometheus/snmp_exporter/pull/843

**Pull request closed without merging**
