### PR TITLE
Add default command line args for target and module

### PR DESCRIPTION
**Pull request by rguliyev**

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is not how the snmp exporter is intended to be used, this should be coming from URL parameters from Prometheus.

**Comment by rguliyev** [comment]
This adds default parameters for people who want to rely on defaults, you can still pass them via URL to override the defaults. This change moves the hardcode of "if_mib" to a definable default, which makes the code cleaner.

**Comment by SuperQ** [comment]
I would like the default module as a flag, that sounds like a good idea, but I don't think a default target is useful.

**Comment by RichiH** [comment]
I can see this being used during manual testing etc, but what is the use
case with service discovering Prometheus?

Not opposed as such, just don't see the use case atm.


Sent by mobile; please excuse my brevity.

**Pull request closed without merging**
