### PR TITLE
feat: add Raritan PDU2-MIB

### PR DESCRIPTION
**Pull request by jvillal-amp**
Add the Raritan PDU2-MIB.txt file.

Also add to `generator.yml` the querying of the external sensors which are found on the Raritan Smart Rack Controller

Closes: #834

Signed-off-by: John L. Villalovos <jvillalovos@amperecomputing.com>

### CODE REVIEW

**Comment by jvillal-amp** [comment]
CI is currently failing due to bug #836

**Comment by SuperQ** [comment]
Can you rebase this?

**Comment by bastischubert** [comment]
this been implemented with #961 , i think we can close this one?

**Comment by jvillal-amp** [comment]
Works for me. Thanks.

**Pull request closed without merging**
