### PR TITLE
Correct typo in README.md

### PR DESCRIPTION
**Pull request by jbd**
Replace RHEL package gcc-g++ with gcc-c++

### CODE REVIEW

**Comment by brian-brazil** [comment]
I don't believe that's a typo, there is such a thing as `gcc-g++`.

**Comment by jbd** [comment]
I didn't spot the package in CentOS 7 or 8.

**Comment by brian-brazil** [comment]
Hmm, I'm not a RH person. Can you confirm it builds with this?

**Comment by jbd** [comment]
From a docker CentOS 8 image, I can run the go build step with those packages : 
```
# yum install golang git gcc make net-snmp net-snmp-utils net-snmp-libs net-snmp-devel
# go get github.com/prometheus/snmp_exporter/generator
# cd ${GOPATH-$HOME/go}/src/github.com/prometheus/snmp_exporter/generator
# go build
```

To run make mibs, I also need p7zip-plugins:

```
# yum install epel-release
# yum install p7zip-plugins
# make mibs
```

**Comment by brian-brazil** [comment]
Let's update it accordingly then. Can you also add the DCO?

**Comment by jbd** [comment]
Replaced by https://github.com/prometheus/snmp_exporter/pull/570

**Pull request closed without merging**
