### PR TITLE
Add support for OctectString indexes.

### PR DESCRIPTION
**Pull request by brian-brazil**
@RichiH

### CODE REVIEW

**Comment by RichiH** [comment]
Thanks! Will test tomorrow.

**Comment by RichiH** [comment]
Both my netscaler-specific and the generic config now barf with `Module 'default' not found in config` on HTTP and `<IP> - - [24/Feb/2016 09:11:38] "GET /metrics?address=<target> HTTP/1.1" 400 -` on CLI.

**Comment by RichiH** [comment]
Disregard the above, it's a consequence of fe70d2739b3d50a8d321266b14df74e1015920f7 which I had not upgraded to in that installations, yet.

**Comment by RichiH** [comment]
Does what it says on the box; good to merge.

**Comment by brian-brazil** [comment]
Great!

**Pull request merged**
