### PR TITLE
Dockerfile for generator: also install snmp-mibs-downloader

### PR DESCRIPTION
**Pull request by huiyiqun**
For up-to-date mibs

### CODE REVIEW

**Comment by brian-brazil** [comment]
That package doesn't contain the vendor MIBs that users typically want, and they may get in the way of the MIBs they're explicitly providing.

**Comment by huiyiqun** [comment]
However, it provide standard MIBs for generic usage.

In fact, I couldn't event resolve oid such as `ifTable`. It's strange, but installing snmp-mibs-downloader solve this problem.

**Comment by brian-brazil** [comment]
You need far more than what snmp-mibs-downloader provides for the included configuration to work.

**Comment by rossigee** [comment]
FWIW, I needed to apply this in order to follow the instructions in the README.md, otherwise it wouldn't resolve 'sysUpTime' or any of the other oids mentioned in the example.

**Comment by cloph** [comment]
definitely needed - while not enough to process the provided generator.yml (which is not the point), it is **required** to process custom MIBs, so I fully support this request.

**Comment by ntavares** [comment]
@brian-brazil I don't understand why this patch hasn't simply been merged, if it solves people's problem. +1 for the merge

**Comment by brian-brazil** [comment]
There's a makefile these days.

**Pull request closed without merging**
