### PR TITLE
Release 0.23.0-rc.0

### PR DESCRIPTION
**Pull request by SuperQ**
BREAKING CHANGES:

This version of the exporter introduces a new configuration file format. This new format separates the walk and metric mappings from the connection and authentication settings. This allows for easier configuration of different auth params without having to duplicate the full walk and metric mapping.

See auth-split-migration.md for more details.

* [CHANGE] Split config of auth and modules #859
* [ENHANCEMENT] Improved Lookup process for label information #908
* [BUGFIX] Fix metrics path not using command-line argument value #904

### CODE REVIEW

**Review by RichiH — CHANGES_REQUESTED** [review]
Reading through auth-split-migration.md again, I realized we didn't show the URL nor how a static file config would look like.

For better or for worse, most networking shops will be stuck in the static file config stage.

I currently don't have a working snmp_exporter setup, or targets, or else I would write & confirm it myself real quick.

**Comment by SuperQ** [comment]
The URL changes are in the README.

**Comment by SuperQ** [comment]
Added a link to the configuration examples to `auth-split-migration.md`.

**Review by RichiH — APPROVED** [review]
LGTM

**Pull request merged**
