### PR TITLE
Add TLS and basic authentication

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
CI isn't happy, you might want to clear your mibs.

**Comment by roidelapluie** [comment]
What do you mean? I don't change anything in that regard

**Comment by roidelapluie** [comment]
updated in a second commit

**Comment by brian-brazil** [comment]
I'm guessing you're on a Mac? You'll need to generate on a different OS, there's something weird with the netsnmp there.

**Comment by roidelapluie** [comment]
I am on linux, net-snmp 5.9

**Comment by roidelapluie** [comment]
I have fixed the issue, CI should become green

**Comment by brian-brazil** [comment]
:+1: 

I had just verified that there's no diff at head.

**Pull request merged**
