### PR TITLE
Add cisco IMC MIBs

### PR DESCRIPTION
**Pull request by ranmalka**
Cisco IMC MIBS to monitor Cisco CUCS server IMC (paralle to HPE-ILO)

@SuperQ 
@bastischubert 
@RichiH 
Signed-off-by: ran rmalka@trigoretail.com

### CODE REVIEW

**Comment by ranmalka** [comment]
I don't know why it failed but on my local files "make generator" worked

**Comment by ranmalka** [comment]
I did it on the local files, and added it to the generator/mib folder

`~/tmp/snmp_exporter/generator cisco_imc_mibs_usc > ls mibs | grep CISCO                                                                                       err 0|1 15:30:56
CISCO-ENTITY-FRU-CONTROL-MIB.my
CISCO-ENTITY-SENSOR-MIB.my
CISCO-ENVMON-MIB.my
CISCO-SMI.my
CISCO-TC.my
CISCO-UNIFIED-COMPUTING-ADAPTOR-MIB.my
CISCO-UNIFIED-COMPUTING-COMPUTE-MIB.my
CISCO-UNIFIED-COMPUTING-EQUIPMENT-MIB.my
CISCO-UNIFIED-COMPUTING-FAULT-MIB.my
CISCO-UNIFIED-COMPUTING-MEMORY-MIB.my
CISCO-UNIFIED-COMPUTING-MGMT-MIB.my
CISCO-UNIFIED-COMPUTING-MIB.my
CISCO-UNIFIED-COMPUTING-NOTIFS-MIB.my
CISCO-UNIFIED-COMPUTING-PROCESSOR-MIB.my
CISCO-UNIFIED-COMPUTING-STORAGE-MIB.my
CISCO-UNIFIED-COMPUTING-TC-MIB.my`

What do you suggest? 

@bastischubert

**Comment by bastischubert** [comment]
"Add a download of the MIB to the Makefile" would be the way to go as of now.

**Comment by ranmalka** [comment]
I will change it,
thanks!

**Pull request closed without merging**
