### PR TITLE
*: support Go modules

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by SuperQ** [comment]
The `generator` phase of the test needs to be in the correct working dir for the make to work.

**Comment by brian-brazil** [comment]
:+1:

**Comment by mjtrangoni** [comment]
@simonpasquier JFTR, running `make` @ master, I am having this:
```sh
$ ./snmp_exporter --version
snmp_exporter, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.11.2
```
Am I missing something?

**Comment by SuperQ** [comment]
Hrm, I'm seeing the same issue. :slightly_frowning_face:

**Comment by simonpasquier** [comment]
@krasi-georgiev also noticed this. I have to dig into it.

**Comment by simonpasquier** [comment]
I might have found something, lets hold on this PR for now.

**Comment by simonpasquier** [comment]
FTR it has been fixed in https://github.com/prometheus/snmp_exporter/pull/362

**Pull request merged**
