### PR TITLE
Add support for IMPLIED indexes

### LINKED ISSUE #305: Handle implied string indexes
### Host operating system: output of `uname -a`
Linux asd 4.16.0-0.bpo.1-amd64 #1 SMP Debian 4.16.5-1~bpo9+1 (2018-05-06) x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
Snmp_exporter-0.11.0.linux-amd64

There seems to be a problem with parsing string length (tmnxSubMgmtSlaProfStatsName). In my case, first character is chopped off and trailer 0x00 remain into output. Issue disappears when index is forced to fixed_size (trailer 0x00 remains ofc but I can probably get rid of it with regexp).

Could it be it's because of TNamedItem which is not picked up (as tmnxSubMgmtSlaProfStatsName remains OctetString and is not turned to DisplayString by generator)?

```
snmpwalk with MIBs loaded:
TIMETRA-SUBSCRIBER-MGMT-MIB::tmnxSubMgmtSlaProfStatsCurr.'HSI' = Counter32: 2459
TIMETRA-SUBSCRIBER-MGMT-MIB::tmnxSubMgmtSlaProfStatsCurr.'HSI+VOIP' = Counter32: 9588
```

```
snmp_exporter without forcing to DisplayString:
tmnxSubMgmtSlaProfStatsCurr{tmnxSubMgmtSlaProfStatsName="0x534900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"} 2459
tmnxSubMgmtSlaProfStatsCurr{tmnxSubMgmtSlaProfStatsName="0x53492B564F49500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"} 9587
```

```
snmp_exporter when forced to DisplayString:
tmnxSubMgmtSlaProfStatsCurr{tmnxSubMgmtSlaProfStatsName="SI����������������������������������������������������������������������"} 2459
tmnxSubMgmtSlaProfStatsCurr{tmnxSubMgmtSlaProfStatsName="SI+VOIP�����������������������������������������������������������������"} 9589
```

As the MIBs are not public, here are the relevant parts:

```
tmnxSubMgmtSlaProfStatsEntry OBJECT-TYPE
    SYNTAX      TmnxSubMgmtSlaProfStatsEntry
    MAX-ACCESS  not-accessible
    STATUS      current
    DESCRIPTION
        "Each row entry represents a set of subscriber mgmt
         SLA-profile statistics."
    INDEX { IMPLIED tmnxSubMgmtSlaProfStatsName }
    ::= { tmnxSubMgmtSlaProfStatsTable 1 }

TmnxSubMgmtSlaProfStatsEntry ::=
    SEQUENCE {
        tmnxSubMgmtSlaProfStatsName      TNamedItem,
        tmnxSubMgmtSlaProfStatsCurr      Counter32,
        tmnxSubMgmtSlaProfStatsPeak      Counter32,
        tmnxSubMgmtSlaProfStatsTimestamp TimeStamp
    }

TNamedItem                       ::= TEXTUAL-CONVENTION
    STATUS      current
    DESCRIPTION
        "The name of an item.  When used as an index to a table, the item
         name uniquely identifies the instance.  When used in a reference
         (TNamedItemOrEmpty) the item name entry must exist in the table.

         Note, use only NVT ASCII displayable characters here, no control
         characters, no UTF-8, etc."
    SYNTAX      DisplayString (SIZE (1..32))

```

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #305

@tarko Can you check if this works for you?

### CODE REVIEW

**Comment by brian-brazil** [comment]
Great, thanks for verifying.

@SuperQ Would you mind reviewing?

**Comment by SuperQ** [comment]
Yup, I already looked at a bit, looks mostly good.

I'm wondering if there's any signal from net-snmp that we can take rather than have this be a manual override.

**Comment by RichiH** [comment]
I am actively trying to forget what I ever had to learn about ASN.1 but IIRC this should be on the wire so even if net-snmp wouldn't expose that today, it should be possible to get that information out.

**Comment by tarko** [comment]
Not an ASN.1 expert by any means but I don't think (and also looking at PCAPs) they are on the wire. It's just a thing described in MIB that tells the parser how to handle specific index.

**Comment by RichiH** [comment]
Meh :(

@cron2 is currently on holiday, but he can probably tell us by heart and reconfirm either way.

**Comment by brian-brazil** [comment]
> I'm wondering if there's any signal from net-snmp that we can take rather than have this be a manual override.

`isimplied` is the signal from net-snmp.

> looks mostly good.

Did you have any particular comments?

**Comment by RichiH** [comment]
If net-snmp knows about IMPLIED, does the generator need to hardcode it into the configuration?

**Comment by tarko** [comment]
Exporter relies on the generated configuration, it does not parse MIBs during runtime

**Comment by brian-brazil** [comment]
The MIB parser part of net-snmp knows about implied.

**Comment by tarko** [comment]
No further discussion emerged, is there a hope it'll get merged soon?

**Comment by SuperQ** [comment]
Sorry, I was traveling last week and didn't have time to finish the review.

**Comment by RichiH** [comment]
It probably makes sense to cut a release for this one.

**Comment by brian-brazil** [comment]
It's already on my todo list. Anything that adds new elements to the config requires a prompt release.

**Comment by SuperQ** [comment]
I'll also send out a vendor bump PR shortly.

**Comment by tarko** [comment]
Thanks to everyone involved.

**Pull request merged**
