### PR TITLE
Switch to kingpin for flags

### PR DESCRIPTION
**Pull request by carlpett**
Continuing the conversions from `flag` to `kingpin`.

### CODE REVIEW

**Comment by brian-brazil** [comment]
You missed the Dockerfile.

The generator also has subcommands, which should be switched over.

**Comment by carlpett** [comment]
I can see the Dockerfile in the diff? Are there more of them?
Didn't see the generator since it didn't use the `flag` package. Will fix it now.

**Comment by brian-brazil** [comment]
That's the only one I noticed.

**Comment by carlpett** [comment]
I've updated to the new common/log as with the others, as well as converted the generator to use kingpin commands.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
