### PR TITLE
the feature which allows to upload config and reload, was developed to snmp_exporter.

### PR DESCRIPTION
**Pull request by bkayranci**
Thanks to the feature, config file can be upload and reload. Also, uploaded config can be permanent if prefer it. @brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. By design the only way to change Prometheus config files is by changing them on disk, if you need this sort of feature you can do so outside of the exporter.

**Comment by bkayranci** [comment]
> Thanks for your PR. By design the only way to change Prometheus config files is by changing them on disk, if you need this sort of feature you can do so outside of the exporter.

Thank you for fast review.

The feature can already change config on disk. It was developed for the scenario following,
Prometheus was configured dynamic target for example file_sd_configs. However snmp_exporter's config can not allow change config file via http request. Thanks to the feature, we can it.

Am i thinking wrong?

**Comment by brian-brazil** [comment]
This feature is explicitly something that we don't want. The only place configuration comes from is disk.

**Comment by bkayranci** [comment]
Thank you for your review. I closed the PR.

**Pull request closed without merging**
