### PR TITLE
Fix for walk on multiple paths

### LINKED ISSUE #671: Bug in the collector for simple walk and get ?
### Host operating system: output of `uname -a`
Linux enzo 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter: error: unknown short flag '-v', try --help
I have cloned from the main branch

### What device/snmpwalk OID are you using?
Zhone GPON

### What did you do that produced an error?

I am very new to SNMP exporter and SNMP as well, so I started small by checking if I can SNMP get two OID's with following snmp.yml
```
gpon:
  walk: [1.3.6.1.4.1.5504.3.1.21.1.3.1.1.5, 1.3.6.1.4.1.5504.2.5.43.1.2.1.2.1]
  metrics:
  - oid: 1.3.6.1.4.1.5504.3.1.21.1.3.1.1.5
    name: modelName
    type: DisplayString
    help: "GPON state"
  - name: gponState
    oid: 1.3.6.1.4.1.5504.2.5.43.1.2.1.2.1
    type: DisplayString
    help: "GPON state"
```

### What did you expect to see?

On running the curl command "curl "http://172.16.23.155:9116/snmp?target=10.100.83.165&module=gpon" I expected to see both modelName and gponState in the output. But I only see gponState.

```
# HELP gponState GPON state
# TYPE gponState gauge
gponState{gponState="Up"} 1
# HELP snmp_scrape_duration_seconds Total SNMP time scrape took (walk and processing).
# TYPE snmp_scrape_duration_seconds gauge
snmp_scrape_duration_seconds 5.55650912
# HELP snmp_scrape_packets_retried Packets retried for get, bulkget, and walk.
# TYPE snmp_scrape_packets_retried gauge
snmp_scrape_packets_retried 1
# HELP snmp_scrape_packets_sent Packets sent for get, bulkget, and walk; including retries.
# TYPE snmp_scrape_packets_sent gauge
snmp_scrape_packets_sent 4
# HELP snmp_scrape_pdus_returned PDUs returned from get, bulkget, and walk.
# TYPE snmp_scrape_pdus_returned gauge
snmp_scrape_pdus_returned 1
# HELP snmp_scrape_walk_duration_seconds Time SNMP walk/bulkwalk took.
# TYPE snmp_scrape_walk_duration_seconds gauge
snmp_scrape_walk_duration_seconds 5.556114617
```

```
level=info ts=2021-06-22T03:18:58.110Z caller=main.go:148 msg="Starting snmp_exporter" version="(version=, branch=, revision=)"
level=info ts=2021-06-22T03:18:58.110Z caller=main.go:149 build_context="(go=go1.16.5, user=, date=)"
level=info ts=2021-06-22T03:18:58.110Z caller=main.go:244 msg="Listening on address" address=:9116
level=info ts=2021-06-22T03:18:58.110Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=debug ts=2021-06-22T03:19:04.001Z caller=main.go:98 module=gpon target=10.100.83.165 msg="Starting scrape"
level=debug ts=2021-06-22T03:19:04.001Z caller=collector.go:215 module=gpon target=10.100.83.165 msg="Walking subtree" oid=1.3.6.1.4.1.5504.3.1.21.1.3.1.1.5
level=debug ts=2021-06-22T03:19:09.057Z caller=collector.go:228 module=gpon target=10.100.83.165 msg="Walk of subtree completed" oid=1.3.6.1.4.1.5504.3.1.21.1.3.1.1.5 duration_seconds=5.055448487s
level=debug ts=2021-06-22T03:19:09.057Z caller=collector.go:215 module=gpon target=10.100.83.165 msg="Walking subtree" oid=1.3.6.1.4.1.5504.2.5.43.1.2.1.2.1
level=debug ts=2021-06-22T03:19:09.557Z caller=collector.go:228 module=gpon target=10.100.83.165 msg="Walk of subtree completed" oid=1.3.6.1.4.1.5504.2.5.43.1.2.1.2.1 duration_seconds=499.925961ms
level=debug ts=2021-06-22T03:19:09.558Z caller=main.go:109 module=gpon target=10.100.83.165 msg="Finished scrape" duration_seconds=5.557137443
```

### What did you see instead?
I expected to see both modelName and gponState.

I am pretty sure I am missing something, but below snippet from collector.go ScrapeTarget function seems incorrect:
```
213         for _, subtree := range config.Walk {
214                 var pdus []gosnmp.SnmpPDU
...
...
...
229
230                 results.pdus = append(result, pdus...) <<<<<<<< append looks wrong
231         }
```

Same when I use pure GET instead of walk in the provided snmp.yml. I don't see any metric though the log says it fetched both oids. No errors.
The code (same function):  
```
171         for len(getOids) > 0 {
172                 oids := len(getOids)
173                 if oids > maxOids {
174                         oids = maxOids
175                 }
..
...
 }
207                 getOids = getOids[oids:]
208         }
209         if len(config.Walk) == 0 {           <<<<<< Added this portion to make it work
210                 results.pdus = result
211         }
212
213         for _, subtree := range config.Walk {
```

### PR DESCRIPTION
**Pull request by mrdunski**
Fixes #671

### CODE REVIEW

**Comment by mrdunski** [comment]
To satisfy [CONTRIBUTING.md](https://github.com/prometheus/snmp_exporter/blob/04b3776ab7ef40e75b6de1843569fc5ebc0121e4/CONTRIBUTING.md):
@SuperQ @RichiH

**Comment by mrdunski** [comment]
I was thinking about it. It is not that easy, since `collector#ScrapeTarget` has no test coverage at all and it wasn't designed with testability in mind.

I could refactor the code to separate SNMP connection handing from the rest of the logic and split it into smaller chunks (since SRP is broken). Then it would be nice to cover all the use cases, but it would increase the scope of that PR from minor one-liner to a bit bigger change.

It might be worth though.

**Comment by mrdunski** [comment]
@SuperQ 
I've noticed that another PR (#674) for this issue was accepted and you haven't review this one.
For the future reference, I'd like to ask if I missed anything in my PR that prevent you from reviewing and accepting it?

I was going to refactor collector#ScrapeTarget and add test coverage, but I'm worried that it won't be reviewed as well.

I guess this one can be closed since it is already fixed.

Thanks.

**Comment by SuperQ** [comment]
Sorry, I just didn't notice this one. My fault.

**Comment by mrdunski** [comment]
Oh, I see. I guess we can close it than.

**Pull request closed without merging**
