### PR TITLE
Hard code version for AirMax devices in generator config

### PR DESCRIPTION
**Pull request by bswinnerton**
This pull request updates the `ubiquiti_airmax` section of the default `snmp.yml` files to be hard coded to use SNMP v1 since that's all that it supports.

I've run into the problem outlined in https://github.com/prometheus/snmp_exporter/issues/313 a few times now, and thought that this might save someone the trouble of investigating in the future.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you change this in the generator and regenerate? Otherwise it'll get lost the next time someone makes a change.

**Comment by bswinnerton** [comment]
> Can you change this in the generator and regenerate? Otherwise it'll get lost the next time someone makes a change.

Ah, I didn't fully understand how this worked. Thank you for explaining @brian-brazil. I've updated the `generator.yml` file, but I don't think that I have the appropriate MIBs to get the default configuration working:

```
$ ./generator generate
INFO[0000] Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp  source="net_snmp.go:135"
WARN[0000] NetSNMP reported 2 parse errors               source="main.go:100"
INFO[0000] Generating config for module arista_sw        source="main.go:49"
FATA[0000] Cannot find oid '1.3.6.1.4.1.30065.3.1.1' to walk  source="tree.go:255"
```

I can manually edit the `snmp.yml` file if you'd like, but I'm not sure that a subsequent run would place the line in the same place.

**Comment by SuperQ** [comment]
@bswinnerton I ran the generator with your change, here's the output:

```
@@ -9759,6 +9759,7 @@ ubiquiti_airmax:
     oid: 1.3.6.1.4.1.41112.1.4.8.4
     type: gauge
     help: Host system temperature - 1.3.6.1.4.1.41112.1.4.8.4
+  version: 1
 ubiquiti_unifi:
   walk:
   - 1.3.6.1.2.1.2
```

**Comment by bswinnerton** [comment]
> I ran the generator with your change, here's the output:

Thanks so much, @SuperQ 🙇.  I've applied the patch.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
