### PR TITLE
Updating Mikrotik-mib to latest version

### PR DESCRIPTION
**Pull request by babinskiy**
Mikrotik-mib's source was updated for pointing to latest version (according to [Mikrotik Wiki](https://wiki.mikrotik.com/wiki/Manual:SNMP#Management_information_base_.28MIB.29))

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO? Is it right that there's no diffs due to this?

**Comment by babinskiy** [comment]
I've added DCO. also I fixed inaccuracy with url,
But I got strange CI error. Could you check it?

**Comment by brian-brazil** [comment]
We've a bit of non-determinism currently, let me kick that.

**Comment by SuperQ** [comment]
Please rebase in order to pick up some fixes to the generator.

**Comment by SuperQ** [comment]
Ping, would you please rebase this change against current to pick up the fixes to the CI pipeline?

**Comment by SuperQ** [comment]
Oh, it looks like there are new features in the new MIB that means you need to generate and update the snmp.yml.

**Comment by babinskiy** [comment]
> 
> 
> Oh, it looks like there are new features in the new MIB 

Yeah, that's why I made PR.

>that means you need to generate and update the snmp.yml.

ok, sure, I'll update it

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
