### PR TITLE
Remove unmaintained example

### PR DESCRIPTION
**Pull request by SuperQ**
We don't generally maintain example service configs in our repos. This is more appropriately handled by prometheus-community/ansible.

Fixes: https://github.com/prometheus/snmp_exporter/issues/832

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
I really don't want to maintain these examples, we don't have any consistency for this stuff on any of our repos.

**Comment by RichiH** [comment]
Semi-random idea: What if we put it into exporter-toolkit?

**Comment by dswarbrick** [comment]
I agree that systemd service files, init scripts etc should really be provided by the distros which package the exporters, since they usually involve distro-specific paths, users / groups, etc.

**Comment by SuperQ** [comment]
Closing this for now.

**Pull request closed without merging**
