### PR TITLE
Add additional OIDs supported by unifi devices

### PR DESCRIPTION
**Pull request by caglar10ur**
Unifi devices exports these system metrics so let's collect them

### CODE REVIEW

**Comment by brian-brazil** [comment]
Do these devices produce useful values for these? I'd expect that they wouldn't have guests or swap.

**Comment by caglar10ur** [comment]
@brian-brazil it varies from device type to device type. AP provides all unifi stats + memory and load. Switch provides only interface stats and nothing else and routers provides additional values like swap space/usage, interrupts/contexts switches and storage.

**Comment by SuperQ** [comment]
This file is really more able examples for device-specific stuff. It's not mean to be generally used as a default everywhere. These are generic OIDs, which I think we want to keep out of the example config.

A few of us have been wanting to build up a more comprehensive SNMP generator example repo, outside of this one.

@caglar10ur  Would you be interested in helping with this?

**Comment by caglar10ur** [comment]
@SuperQ FWIW those OIDs are already in the generator.yml file either referred by their name (https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml#L145) or by their OIDs (https://github.com/prometheus/snmp_exporter/blob/master/generator/generator.yml#L194) :)

That said I totally understand you wanting to keep generator.yml file just as an example. I'm not sure how can I help with that other comprehensive repo you mentioned but I'm sure I'll be able to see what that repo offiers and adjust it for UBNT/test here with my setup and send PRs if needed.

Please feel free to close this!

**Comment by SuperQ** [comment]
@caglar10ur I'm testing this out on some Unifi APs I have. I'm not getting anything from `systemStats`. Are you sure this is supported?

**Comment by caglar10ur** [comment]
@SuperQ 🤦‍♂️ - it must be a left over - yes, I'm also not getting anything for systemStats. I'll drop it and re-generate

```
# snmpwalk -On -v 1 -m +UBNT-MIB:UBNT-UniFi-MIB -c public router.skynet | grep 1.3.6.1.4.1.2021
# snmpwalk -On -v 1 -m +UBNT-MIB:UBNT-UniFi-MIB -c public switch.skynet | grep 1.3.6.1.4.1.2021
# snmpwalk -On -v 1 -m +UBNT-MIB:UBNT-UniFi-MIB -c public ap.skynet | grep 1.3.6.1.4.1.2021
# 
```

**Comment by caglar10ur** [comment]
Oh wait - actually I'm getting systemStats - snmpwalk was giving an error that I missed

```
curl http://minime.skynet:9116/snmp\?target\=192.168.1.1\&module\=ubiquiti_unifi | grep ^ss
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28900  100 28900    0     0  24595      0  0:00:01  0:00:01 --:--:-- 245ssCpuIdle 89
95
ssCpuRawGuest 0
ssCpuRawGuestNice 0
ssCpuRawIdle 4.18307848e+08
ssCpuRawInterrupt 0
ssCpuRawKernel 0
ssCpuRawNice 0
ssCpuRawSoftIRQ 3.972002e+06
ssCpuRawSteal 0
ssCpuRawSystem 9.723732e+06
ssCpuRawUser 1.1652534e+07
ssCpuRawWait 12315
ssCpuSystem 3
ssCpuUser 6
ssErrorName{ssErrorName="systemStats"} 1
ssIORawReceived 2.301736e+06
ssIORawSent 528056
ssIOReceive 0
ssIOSent 0
ssIndex 1
ssRawContexts 4.55405849e+08
ssRawInterrupts 9.60154113e+08
ssRawSwapIn 0
ssRawSwapOut 0
ssSwapIn 0
ssSwapOut 0
ssSysContext 240
ssSysInterrupts 337```

**Comment by SuperQ** [comment]
Strange, I get nothing from my UAP-PRO and UAP-AC-PRO APs.  I'm running a pretty current `4.0.15.9872` AP firmware version. :frowning:

**Comment by caglar10ur** [comment]
@SuperQ yup, APs don't export these.

As I wrote in the https://github.com/prometheus/snmp_exporter/pull/374#issuecomment-454083419 - only my router (UniFi Security Gateway 3P - 4.4.36.5146617) exports these. My switch (UniFi Switch 8 POE-60W- 4.0.15.9872) and APs (UniFi AP-AC-Pro - 4.0.15.9872) does not have them.

**Comment by caglar10ur** [comment]
@SuperQ another idea would be making unifi router/switch and aps different targets (maybe in the new repo that you mentioned) so that they can have their own OID sets.

**Comment by SuperQ** [comment]
Ohhhh, I'm an idiot. :disappointed: Sorry. That's really annoying that they don't have the proper data on the APs.

Yea, I typically configure separate modules for them.

I wonder if I could get [this opkg](https://github.com/openwrt/packages/tree/master/utils/prometheus-node-exporter-lua) running on the APs.

**Comment by caglar10ur** [comment]
@SuperQ no worries! I also got confused for a sec as well. I blame lack of ☕️ :)

I'm sure that would run fine on the AP, if I remember correctly @mdlayher also have a unifi_exporter somewhere that is written in go and exports metrics to prometheus. I ran filebeat/metricbeat on them for a while but then gave up running anything special since they got nuked in every firmware upgrade and decided to stick with snmp (hence this PR :P)

I also started to work on some grafana boards if you are interested (https://github.com/caglar10ur/homelab/blob/master/config/grafana/provisioning/dashboards/unifi.json) that is AP only for now and most probably have hardcoded values for my environment.

I'll take a look at the new repo hopefully later today :)

**Comment by caglar10ur** [comment]
@SuperQ have you had a chance to decide how you are going to lay out the repo? Are you planning to just have the generator config and its corresponding snmp.yml there?

**Comment by brian-brazil** [comment]
So do we want these OIDs or not? Are they actually useful, or more stamp collecting?

**Comment by SuperQ** [comment]
No, I don't think we want to expand the unifi section to include `UCD-SNMP-MIB` metrics.

**Pull request closed without merging**
