### PR TITLE
Drop metrics for label lookups

### PR DESCRIPTION
**Pull request by SuperQ**
Remove metrics in if_mib that are part of the lookups.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Partial fix for https://github.com/prometheus/snmp_exporter/issues/414

CC @candlerb

**Comment by SuperQ** [comment]
`ifIndex` is also a bit useless, possibly worth dropping.

**Comment by candlerb** [comment]
I have tested the new generated `snmp.yml`, and I confirm this drops the ifName/ifDescr/ifAlias metrics as desired - thank you!

I don't have a particular use for ifIndex.  It *does* give a static mapping between names and indexes which you can depend on independently of any particular metric (e.g. if you needed to join on it).  But since every metric is already labelled with ifIndex, ifName, ifDescr and ifAlias, I don't think it's needed in practice.

**Comment by brian-brazil** [comment]
We should leave ifIndex, some other tables tend to have the value and users may need to do == on it.

**Pull request merged**
