### PR TITLE
Fix exporter metrics

### PR DESCRIPTION
**Pull request by SuperQ**
Move exporter metric definitions and registration out of the collector
package and into the main package. This fixes metrics always being empty
due to the epehemeral collector registry.

Fixes: https://github.com/prometheus/snmp_exporter/issues/950

### CODE REVIEW

**Comment by candlerb** [comment]
Erm, I'm not sure this is complete.

`collector.New()` is called on every scrape, and it creates (and registers) a new instance of internalMetrics each time:

```
func New(... reg prometheus.Registerer ...) *Collector {
        internalMetrics := newInternalMetrics(reg)
        return &Collector{ctx: ctx, target: target, authName: authName, auth: auth, modules: modules, logger: logger, metrics: internalMetrics, concurrency: conc}
}
```

**Comment by SuperQ** [comment]
Yea, I realized it after I pushed. Reworked, tested locally.

**Comment by SuperQ** [comment]
:eyeglasses: @servak

I realized I made a mistake in the review of the multi-module support. The metrics for the SNMP data actually belong to the `main` package, since they're exporter-level stats. Move the definitions of these metrics back to the main package and pass them in as handles.

This is similar to what we did in the blackbox_exporter in order to make the collection packages reusable as a library.

https://github.com/prometheus/blackbox_exporter/pull/1060

**Comment by servak** [comment]
@SuperQ Thanks for letting me know.

Memo:
scrape metrics -> /snmp
global metrics → /metrics

ExporterMetrics basically has global metrics, but only snmp_collection_duration_seconds is left in collector, is there any reason for that?
If snmp_collection_duration_seconds is moved to ExporterMetrics, the collector.InitModuleMetrics function can be removed.

**Comment by SuperQ** [comment]
@servak Finished moving the collection duration metric to main.

**Comment by servak** [comment]
@SuperQ LGTM

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
