### PR TITLE
Warning comment on snmp.yaml being auto-generated

### LINKED ISSUE #326: Header blurb for snmp.yml
Generator should put a warning stanza about this config being autogenerated at the top of snmp.yml

### PR DESCRIPTION
**Pull request by sgissi**
Add a warning comment on snmp.yaml file being auto-generated. Fixes #326.

Signed-off-by: Silvio Gissi <silvio@gissilabs.com>

### CODE REVIEW

**Comment by sgissi** [comment]
Input on the warning text welcome :) @brian-brazil @RichiH

**Comment by RichiH** [comment]
Maybe "manual changes will be lost" at the end; people are free to edit it if they think they know what they do. Else LGTM

**Comment by SuperQ** [comment]
Should we make the warning message be a command line flag? Then @RichiH can add his usual ascii art.

**Comment by brian-brazil** [comment]
I think that might be going a little too far. If someone wants to adjust it it's probably part of a pipeline/script and they can tweak it there.

**Comment by sgissi** [comment]
I quite like the "manual changes will be lost" instead of "do not edit". If it is Ok, I can update the text and also make sure that snmp.yaml in the repo is updated to make CircleCI happy.

**Comment by SuperQ** [comment]
I would prefer keeping it simple and short.  Just `# This file was created using the snmp_exporter generator.`

**Comment by RichiH** [comment]
We are descending into bikeshedding, but I maintain that all messages should not only be factually correct, but also useful and/or actionable.

**Comment by brian-brazil** [comment]
For me as long as it points to the generator and says it's auto-generated, I think its okay.

**Comment by sgissi** [comment]
PTAL @RichiH @brian-brazil @SuperQ

**Comment by RichiH** [comment]
Thanks!

**Pull request merged**
