### PR TITLE
Add missing CPU, Load and Storage OIDs

### PR DESCRIPTION
**Pull request by jayme-github**
Sorry @brian-brazil - I missed some. :slightly_frowning_face:

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

**Comment by Svedrin** [comment]
this is a bit odd... I tried to add the very same metrics to SNMP exporter a while back so I could scrape my linux boxes more easily which have snmpd deployed already, without needing to deploy node_exporter everywhere. So now I just need to tell snmp_exporter that everything's a Synology NAS and it'll happily scrape the values for me? that doesn't sound right :/ maybe the CPU and storage parts could be split out into a more generic module?

**Comment by brian-brazil** [comment]
If you can use the node exporter you should. SNMP is inferior in many many ways.

**Comment by juliusv** [comment]
The context on IRC from @Svedrin was:

> when I proposed to add disk/cpu metrics to snmp-exporter that proposal was rejected due to "we want you to use node-exporter for that" reasons, but now the very same metrics have been added to the synology module... so I just have to tell snmp-exporter that my linux box is a synology NAS and it'll happily scrape the values for me?

So I guess the question was why allow CPU/disk metrics for Synology, but not for other things. Is it not possible to run node exporter on Synology? Just wondering about the consistency of the decision.

**Comment by SuperQ** [comment]
I originally suggested that using the node_exporter on the Synology was the best path.  Using SNMP for this is not what I would recommend.

**Pull request merged**
