### PR TITLE
Remove Eaton from examples

### PR DESCRIPTION
**Pull request by SuperQ**
Eaton has made their MIBs incaccessible to our CI. So remove them from the examples.
* Also rollback Cisco I'm not sure MIBs due to recent breakage.
* 
Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by Nexucis** [comment]
perhaps we should wait a bit before merging this PR, just to see if they are going to fix it quickly. Perhaps then this PR won't be required anymore

**Comment by SuperQ** [comment]
It's been broken for months, I'm not expecting anything soon.

**Review by Nexucis — APPROVED** [review]
alright, let's move forward then. We can always revert this PR if one day it's fixed.

**Comment by SuperQ** [comment]
Yup, hopefully they fix it eventually.

**Pull request merged**
